# Generated by Django 3.1 on 2020-08-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200821_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
